<?php
/**
 * Constants
 *
 * @author Grégoire Favreau - mohinette@hotmail.fr
 * @version 1.0
 */

/**
 * Configuration de MeetSong
 */
 define('URL', 'http://localhost/MeetSong');
 define('PATH', '/');
 define('LANGUAGE', 'fr');
 define('TITRE', 'MeetSong');
 define('CLE', '');
 
 /**
  * Configuration de la base de données
  */
define('TYPE', 'mysql');
define('HOTE', 'localhost');
define('PSEUDO', 'meetsong');
define('MDP', '');
define('NOM', 'root');
define('PREFIX', 'meetsong_');

/**
 * Configuration des sessions
 */
 define('SESSION_PREFIX', 'meetsong_');

/**
 * Configuration pour les authentifications
 */

/**
 * Setup the Config API Mode.
 * For using the 'database' mode, you need to have a database, with a table generated by 'scripts/nova_options'
 */
define('CONFIG_STORE', 'files'); // Supported: "files", "database"

